.align 2
voicegroup191::
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 165, 51, 242 @ Glockenspiel
	voice_keysplit_all voicegroup002 @ Drums
	voice_directsound 60, 0, violin, 255, 255, 0, 221 @ Violin
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 15, 0 @ Square
	voice_keysplit voicegroup009, KeySplitTable5 @ French Horn
	voice_keysplit voicegroup006, KeySplitTable2 @ string ensemble
	voice_directsound 60, 0, violin, 255, 255, 0, 221 @ Violin
	voice_keysplit voicegroup009, KeySplitTable5 @ French Horn
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_piano1_72, 255, 250, 0, 221 @ Piano