gText_Birch_Welcome:: @ 82C897B
	.string "Oh, hey! Nice to meet you!\p"
	.string "Welcome to the world of Pokémon!\p"
	.string "My name is Sakura.\p"
	.string "I'm a Pokémon Professor! That's pretty\n"
	.string "cool, huh?\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "This is what we call a “Pokémon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "Here in Rika, we have a really diverse\n"
	.string "region full of all kinds of Pokémon!\p"
	.string "Trainers from all over the world travel\n"
	.string "here to catch Pokémon and challenge\l"
	.string "each other in battle!\p"
	.string "In fact, the Pokémon Trainers in Rika\n"
	.string "are the toughest around!\p"
	.string "The Pokémon League here in Rika only\n"
	.string "just started, and people are even more\l"
	.string "amped up than usual to duke it out!\p"
	.string "When I see battles, I just can't help\n"
	.string "but to record data for my research!\p"
	.string "So many Pokémon... and so very many\n"
	.string "possibilities! Oh, isn't it exciting?!\p"
	.string "...Ahem, sorry! I tend to get a little\n"
	.string "too into Pokémon sometimes.\p"
	.string "But enough about me... What about you?\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "Please, do tell me...$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "Fantastic!\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Wonderful!\p"
	.string "You're {PLAYER}{KUN}, and you turned ten\n"
	.string "a few days ago?\p"
	.string "Aw yeah, that sounds like an adventure\n"
	.string "just waiting to happen!\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "{PLAYER}, are you ready for this?\p"
	.string "You're about to start on a life-changing\n"
	.string "journey, my friend!\p"
	.string "Come with me, into the world of Pokémon!\n"
	.string "You'll travel, make new friends, and\l"
	.string "find new mysteries to uncover!\p"
	.string "Welcome, {PLAYER}, to a new adven-\p"
	.string ". . . . . . . . . . . . . . . . . . . .\p"
	.string "What? Yes, I know I'm almost out of\n"
	.string "data! Gah! Could you not just give me...\p"
	.string "Eheheheh, sorry, {PLAYER}! My assistant\n"
	.string "is reminding me that my phone's data\l"
	.string "plan isn't unlimited, so...\p"
	.string "I hate video calls... now, how do you...\p"
	.string "Got it!$"
