.set LOCALID_TIANA, 4

Route102_MapScripts:: @ 81EC0E0
	map_script MAP_SCRIPT_ON_TRANSITION, Route2Transition
	.byte 0

Route2Transition:
	call_if_set FLAG_ROUTE_2_RAINING, Route2Raining
	end

Route102_EventScript_LittleBoy:: @ 81EC0E1
	msgbox Route102_Text_ImNotVeryTall, MSGBOX_NPC
	end

Route102_EventScript_RouteSignOldale:: @ 81EC0EA
	msgbox Route102_Text_RouteSignOldale, MSGBOX_SIGN
	end

Route102_EventScript_RouteSignPetalburg:: @ 81EC0F3
	msgbox Route102_Text_RouteSignPetalburg, MSGBOX_SIGN
	end

Route102_EventScript_Boy:: @ 81EC0FC
	msgbox Route102_Text_CatchWholeBunchOfPokemon, MSGBOX_NPC
	end

Tiana1::
	setflag FLAG_ROUTE_2_RAINING
	setweather WEATHER_RAIN_THUNDERSTORM
	doweather
	setvar VAR_ROUTE102_STATE, 1
	end

Tiana2::
	setflag FLAG_ROUTE_2_RAINING
	setweather WEATHER_RAIN_THUNDERSTORM
	doweather
	setvar VAR_ROUTE102_STATE, 1
	end

Tiana3::
	setflag FLAG_ROUTE_2_RAINING
	setweather WEATHER_RAIN_THUNDERSTORM
	doweather
	setvar VAR_ROUTE102_STATE, 1
	end

Route102_EventScript_Calvin:: @ 81EC105
	trainerbattle_single TRAINER_ED, Route102_Text_CalvinIntro, Route102_Text_CalvinDefeated, Route102_EventScript_CalvinRegisterMatchCallAfterBattle
	msgbox Route102_Text_CalvinPostBattle, MSGBOX_DEFAULT
	release
	end

Route102_EventScript_CalvinRegisterMatchCallAfterBattle:: @ 81EC146
	special PlayerFaceTrainerAfterBattle
	waitmovement 0
	goto_if_set FLAG_HAS_MATCH_CALL, Route102_EventScript_CalvinRegisterMatchCall
	release
	end

Route102_EventScript_CalvinRegisterMatchCall:: @ 81EC157
	msgbox Route102_Text_CalvinRegisterShort, MSGBOX_DEFAULT
	register_matchcall TRAINER_CALVIN_1
	release
	end

Route102_EventScript_CalvinTryRegister:: @ 81EC170
	goto_if_set FLAG_HAS_MATCH_CALL, Route102_EventScript_CalvinRegister
	msgbox Route102_Text_CalvinPostBattle, MSGBOX_DEFAULT
	release
	end

Route102_EventScript_CalvinRegister:: @ 81EC183
	msgbox Route102_Text_CalvinRegister, MSGBOX_DEFAULT
	register_matchcall TRAINER_CALVIN_1
	release
	end

Route102_EventScript_CalvinRematch:: @ 81EC19C
	trainerbattle_rematch TRAINER_CALVIN_1, Route102_Text_CalvinRematchIntro, Route102_Text_CalvinRematchDefeated
	msgbox Route102_Text_CalvinRematchPostBattle, MSGBOX_AUTOCLOSE
	end

Route102_EventScript_Rick:: @ 81EC1B3
	trainerbattle_single TRAINER_FREDRICK, Route102_Text_RickIntro, Route102_Text_RickDefeated
	msgbox Route102_Text_RickPostBattle, MSGBOX_AUTOCLOSE
	end

Route102_EventScript_Tiana:: @ 81EC1CA
	trainerbattle_single TRAINER_ALBERTO, Route102_Text_TianaIntro, Route102_Text_TianaDefeated
	goto_if_set FLAG_ROUTE_2_RAINING, PostBattleRain
	msgbox Route102_Text_TianaPostBattleNoRain, MSGBOX_AUTOCLOSE
	releaseall
	end

PostBattleRain::
	msgbox Route102_Text_TianaPostBattleRain, MSGBOX_AUTOCLOSE
	end

Route102_EventScript_Allen:: @ 81EC1E1
	trainerbattle_single TRAINER_DECLAN, Route102_Text_AllenIntro, Route102_Text_AllenDefeated
	msgbox Route102_Text_AllenPostBattle, MSGBOX_AUTOCLOSE
	end

Route102_Text_WatchMeCatchPokemon: @ 81EC1F8
	.string "WALLY: {PLAYER}…\n"
	.string "POKéMON hide in tall grass like this,\l"
	.string "don't they?\p"
	.string "Please watch me and see if I can\n"
	.string "catch one properly.\p"
	.string "…Whoa!$"

Route102_Text_WallyIDidIt: @ 81EC271
	.string "WALLY: I did it… It's my…\n"
	.string "My POKéMON!$"

Route102_Text_LetsGoBack: @ 81EC297
	.string "{PLAYER}, thank you!\n"
	.string "Let's go back to the GYM!$"

Route102_Text_ImNotVeryTall: @ 81EC2C0
	.string "Y'know, you can jump over these ledges\n"
	.string "to get back faster! Try it out!$"

Route102_Text_CatchWholeBunchOfPokemon: @ 81EC32E
	.string "The Trainers here have been itching for\n"
	.string "a fight all day. My Pokémon are in no\l"
	.string "shape to get me to Spectre City!$"

Route102_Text_RouteSignOldale: @ 81EC35B
	.string "Route 2\p"
	.string "Taproot Town {DOWN_ARROW}$"

Route102_Text_RouteSignPetalburg: @ 81EC373
	.string "Route 2\p"
	.string "Route 3 {RIGHT_ARROW}$"
